// public-ui/src/app/data-browser/views/pm/pm.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription as ISubscription } from 'rxjs/internal/Subscription';
import { environment } from '../../../../environments/environment';
import { DataBrowserService } from '../../../../publicGenerated/api/dataBrowser.service';
import { Analysis } from '../../../../publicGenerated/model/analysis';
import { ConceptGroup } from '../../../utils/conceptGroup';
import { ConceptWithAnalysis } from '../../../utils/conceptWithAnalysis';
import { DbConfigService } from '../../../utils/db-config.service';
import { DomainType } from '../../../utils/enum-defs';
import { TooltipService } from '../../services/tooltip.service';

@Component({
  selector: 'app-physical-measurements',
  templateUrl: './pm.component.html',
  styleUrls: ['../../../styles/template.css', '../../../styles/cards.css', './pm.component.css']
})
export class PhysicalMeasurementsComponent implements OnInit, OnDestroy {
  title = 'Browse Program Physical Measurements';
  pageImage = '/assets/db-images/man-standing.png';
  private subscriptions: ISubscription[] = [];
  loadingStack: any = [];
  ageChartTitle = 'Age When Physical Measurement Was Taken';
  bsChartTitle = 'Sex Assigned At Birth';
  domainCountAnalysis: any;
  testReact: boolean;
  reactChart: boolean;
  // Todo put constants in a class for use in other views
  chartType = 'bar';

  // Total analyses
  genderAnalysis: Analysis = null;
  raceAnalysis: Analysis = null;
  ethnicityAnalysis: Analysis = null;

  selectedConceptUnit: string;

  unitNames = [];

  // Get the physical measurement groups array we display here
  conceptGroups: ConceptGroup[];
  // Initialize to first group and concept, adjust order in groups array above
  selectedGroup: ConceptGroup;
  selectedConcept: ConceptWithAnalysis;
  selectedConceptValueAnalysis: Analysis;
  selectedConceptValueCountAnalysis: Analysis;
  domainType = DomainType.PHYSICAL_MEASUREMENTS;
  searchText: string = null;

  // we save the total gender counts
  femaleCount = 0;
  maleCount = 0;
  otherCount = 0;

  pmGroups: any;

  constructor(private api: DataBrowserService, public dbc: DbConfigService,
    private tooltipText: TooltipService) {

  }

  loading() {
    return this.loadingStack.length > 0;
  }

  ngOnInit() {
    this.testReact = environment.testReact;
    this.reactChart = environment.reactChart;
    this.searchText = localStorage.getItem('searchText');
    this.pmGroups = this.dbc.pmGroups;

    // Get demographic totals
    this.loadingStack.push(true);
    this.subscriptions.push(this.api.getConceptAnalysisResults(this.dbc.PM_CONCEPTS.map(String))
      .subscribe({
        next: result => {
          const items = result.items;
          this.conceptGroups = this.dbc.pmGroups;
          for (const g of this.conceptGroups) {
            for (const c of g.concepts) {
              if (c.conceptId === '903133') {
                // Hardcoding the order of units for height pm
                const sortOrder = ['centimeter', 'inch (us)'];
                items.filter(i => i.conceptId === c.conceptId)[0].measurementGenderCountAnalysis
                .sort((a, b) => {
                    return sortOrder.indexOf(a.unitName.toLowerCase()) -
                    sortOrder.indexOf(b.unitName.toLowerCase());
                });
              }
              const matchedItem = items.filter(i => i.conceptId === c.conceptId);
              c.analyses = matchedItem.length > 0 ? matchedItem[0] : null;
              this.arrangeConceptAnalyses(c);
            }
          }
          if (this.searchText) {
            this.selectedGroup = this.conceptGroups.filter(conceptgroup =>
              conceptgroup.groupName.toLowerCase().
                includes(this.searchText.toLowerCase()))[0];
          } else {
            this.selectedGroup = this.conceptGroups[0];
          }
          this.showMeasurement(this.selectedGroup, this.selectedGroup.concepts[0]);
          this.loadingStack.pop();
        },
        error: err => {
          this.loadingStack.pop();
          console.log('Error: ', err);
        }
      }));
    this.loadingStack.push(true);
    this.subscriptions.push(this.api.getCountAnalysis('Physical Measurements', 'pm')
      .subscribe({
        next: result => {
          this.domainCountAnalysis = result;
          this.loadingStack.pop();
        },
        error: err => {
          this.loadingStack.pop();
          console.log('Error: ', err);
        }
      }));
  }

  ngOnDestroy() {
    for (const s of this.subscriptions) {
      s.unsubscribe();
    }
  }

  showMeasurement(group: any, concept: any) {
    this.selectedGroup = group;
    this.selectedConcept = concept;
    console.log(this.selectedConcept);
    if (this.selectedConcept && this.selectedConcept.analyses &&
      this.selectedConcept.analyses.measurementGenderCountAnalysis) {
      this.unitNames = [];
      for (const r of this.selectedConcept.analyses.measurementGenderCountAnalysis) {
        let tempUnitNames = r.results.map(({ stratum2 }) => stratum2);
        tempUnitNames = tempUnitNames.filter(
          function (elem, index, self) {
            return index === self.indexOf(elem);
          });
        this.unitNames.push(...tempUnitNames);
      }
    }
    if (this.unitNames) {
      this.selectedConceptUnit = this.unitNames[0];
      if (this.selectedConceptUnit) {
        this.setAnalysis();
      }
    }
    console.log(this.selectedConcept);
    this.dbc.triggerEvent('conceptClick', 'Physical Measurement', 'Click',
      concept.conceptName + ' - ' + 'Physical Measurements', this.searchText, null);
  }

  setAnalysisStratum(results: any) {
    for (const r of results) {
      if (r.analysisStratumName === null) {
        r.analysisStratumName = this.dbc.GENDER_STRATUM_MAP[r.stratum3];
      }
    }
  }

  public getCountAnalysis(conceptUnit: any) {
    const genderSort = ['Male', 'Female', 'Other'];
    return this.selectedConcept.analyses.measurementGenderCountAnalysis.filter(
      r => r.unitName === this.selectedConceptUnit)[0].results
      .sort((a, b) => {
        return genderSort.indexOf(a.analysisStratumName) -
          genderSort.indexOf(b.analysisStratumName);
      });
  }

  arrangeConceptAnalyses(concept: any) {
    if (concept.analyses.genderAnalysis) {
      this.organizeGenders(concept);
    }

    let genders = [this.dbc.MALE_GENDER_ID, this.dbc.FEMALE_GENDER_ID, this.dbc.OTHER_GENDER_ID];
    let prevResult;
    for (const gca of concept.analyses.measurementGenderCountAnalysis) {
      if (gca.results.length < 3) {
        for (const result of gca.results) {
          prevResult = result;
          genders = genders.filter(item => item !== result.stratum3);
        }
        for (const gender of genders) {
          const missingResult = { ...prevResult };
          missingResult.stratum3 = gender;
          missingResult.countValue = 20;
          missingResult.sourceCountValue = 20;
          gca.results.push(missingResult);
        }
      }
      this.setAnalysisStratum(gca.results);
    }

  }

  organizeGenders(concept: ConceptWithAnalysis) {
    const analysis: Analysis = concept.analyses.genderAnalysis;
    let male = null;
    let female = null;
    let other = null;

    // No need to do anything if only one gender
    if (analysis.results.length <= 1) {
      return;
    }
    const results = [];
    for (const g of analysis.results) {
      if (g.stratum2 === this.dbc.MALE_GENDER_ID) {
        male = g;
      } else if (g.stratum2 === this.dbc.FEMALE_GENDER_ID) {
        female = g;
      } else if (g.stratum2 === this.dbc.OTHER_GENDER_ID) {
        other = g;
      }
    }

    // Order genders how we want to display  Male, Female , Others
    if (male) { results.push(male); }
    if (female) { results.push(female); }
    if (other) { results.push(other); }
    analysis.results = results;
  }

  setUnit(unit) {
    this.selectedConceptUnit = unit;
    this.setAnalysis();
  }

  setAnalysis() {
    if (['903120', '903111'].indexOf(this.selectedConcept.conceptId) === -1) {
      let temp = this.selectedConcept.analyses.measurementValueGenderAnalysis.filter(
        a => a.unitName.toLowerCase() ===
          this.selectedConceptUnit.toLowerCase());
      this.selectedConceptValueAnalysis = temp[0];
      temp = this.selectedConcept.analyses.measurementGenderCountAnalysis.filter(
        a => a.unitName.toLowerCase() ===
          this.selectedConceptUnit.toLowerCase());
      this.selectedConceptValueCountAnalysis = temp[0];
    }
  }

  public hoverOnTooltip(label: string, action: string) {
    this.dbc.triggerEvent('tooltipsHover', 'Tooltips', 'Hover',
      label, null, action);
  }

  getValueAnalysis() {
    if (!this.selectedConceptValueAnalysis) {
      return this.selectedConcept.analyses.measurementValueGenderAnalysis[0];
    }
    return this.selectedConceptValueAnalysis;
  }
}


<div class="pm-container">
  <h1>{{title}}</h1>
  <div class="pm-layout">
    <aside>
      <div *ngFor="let item of conceptGroups;" class="button-item">
        <button (click)="showMeasurement(item, item.concepts[0])" [ngClass]="{active:selectedGroup === item}"
          class="btn btn-link"> {{item.groupName}} </button>
      </div>
    </aside>
    <app-spinner [loading]="loading()"></app-spinner>
    <div class="db-card" *ngIf="!loading()">
      <div class="db-card-inner">
        <div class="db-card-header">
          <div class="group-name">{{selectedGroup.groupName}}</div>
          <div class="bs-title" *ngIf="this.selectedConcept && this.selectedConcept.analyses && this.selectedConcept.analyses.measurementValueGenderAnalysis">{{bsChartTitle}}
            <app-tooltip-react *ngIf="testReact"
                               [tooltipKey]="'pmValueChartHelpText'"
                               [label]="'Physical Measurements tooltip hover'" [searchTerm]="searchText"
                               [action]="'Hover on pm biological sex chart of concept' + selectedGroup"></app-tooltip-react>
            <app-tooltip [tooltipKey]="'pmValueChartHelpText'"
                         [label]="'Physical Measurements tooltip hover'" [searchTerm]="searchText"
                         [action]="'Hover on pm biological sex chart of concept' + selectedGroup"></app-tooltip>
          </div>
          <div class="group-option" *ngIf="selectedGroup && selectedGroup.concepts && selectedGroup.concepts.length > 1">
            <button *ngFor="let c of selectedGroup.concepts" [ngClass]="{active:selectedConcept === c}"
              (click)="showMeasurement(selectedGroup, c)" class="btn btn-link">{{c.conceptName}} </button>
          </div>
        </div>
        <ng-container *ngIf="unitNames && unitNames.length > 1">
          <div class="group-unit">
            <button *ngFor="let u of unitNames" [ngClass]="{active:selectedConceptUnit === u}" (click)="setUnit(u)" class="btn btn-link unit-button">{{u}}</button>
          </div>
        </ng-container>
        <div *ngIf="selectedConcept && (selectedConcept.conceptId === '903111' || selectedConcept.conceptId === '903120')" class="participant-count">
          <ng-container *ngIf="selectedConcept.analyses.countAnalysis.results[0].countValue > 20;then pmGE20;else pmLE20">
          </ng-container>
          <ng-template #pmGE20>
            Total Participant count: {{selectedConcept.analyses.countAnalysis.results[0].countValue | number}}
          </ng-template>
          <ng-template #pmLE20>
            Total Participant count: &le; {{selectedConcept.analyses.countAnalysis.results[0].countValue | number}}
          </ng-template>
        </div>
        <div class="chart-layout"
          *ngIf="selectedConcept && selectedConcept.analyses && selectedConcept.analyses.measurementGenderCountAnalysis">
          <!-- Loop through the genders we have results for showing the graph -->
          <ng-container *ngIf="['903120','903111'].indexOf(selectedConcept.conceptId) === -1; else stackedChart">
            <div class="bs-chart-item" *ngFor="let gender of getCountAnalysis(selectedConceptUnit)">
              <div *ngIf="[dbc.FEMALE_GENDER_ID, dbc.MALE_GENDER_ID, dbc.OTHER_GENDER_ID].includes(gender.stratum3) && selectedConcept.analyses &&
              selectedConcept.analyses.measurementGenderCountAnalysis" class="chart-title">
                <span class="chart-title" *ngIf="gender.countValue > 20; else PmChartTitleLE20">
                  {{gender.analysisStratumName}} – {{gender.countValue.toLocaleString()}}</span>
                <ng-template #PmChartTitleLE20>{{gender.analysisStratumName}} – &le; {{gender.countValue.toLocaleString()}}</ng-template>
              </div>
              <app-chart [genderId]="gender.stratum3"
                         [chartTitle]="gender.analysisStratumName + ' - ' + gender.countValue.toLocaleString()"
                         [chartType]="selectedConcept.chartType"
                         [analysis]="getValueAnalysis()"
                         [conceptId]="selectedConcept.conceptId"
                         [domainCountAnalysis]="domainCountAnalysis">
              </app-chart>
            </div>
          </ng-container>
          <ng-template #stackedChart>
            <div class="chart-item stacked-chart-item">
              <app-chart *ngIf="selectedConcept.analyses.measurementValueGenderAnalysis" [conceptId]="selectedConcept.conceptId"
                         [analysis]="selectedConcept.analyses.measurementValueGenderAnalysis[0]"
              [participantCount]="selectedConcept.analyses.countAnalysis.results[0].countValue"
              [domainCountAnalysis]="domainCountAnalysis">
              </app-chart>
            </div>
          </ng-template>
          <!-- show Age totals -->
          <div class="chart-item age-chart" *ngIf="selectedConcept.analyses && selectedConcept.analyses.ageAnalysis">
            <div>{{ageChartTitle}}
              <app-tooltip-react *ngIf="testReact"
                                 [tooltipKey]="'pmAgeChartHelpText'"
                                 [label]="'Physical Measurements tooltip hover'" [searchTerm]="searchText"
                                 [action]="'Hover on pm age chart of concept' + selectedConcept.conceptName"></app-tooltip-react>
              <app-tooltip *ngIf="!testReact" [tooltipKey]="'pmAgeChartHelpText'"
              [label]="'Physical Measurements tooltip hover'" [searchTerm]="searchText"
                           [action]="'Hover on pm age chart of concept' + selectedConcept.conceptName"></app-tooltip>
            </div>
            <app-age-chart-react *ngIf="reactChart; else angAgeChart" [ageAnalysis]="selectedConcept.analyses.ageAnalysis" [ageCountAnalysis]="domainCountAnalysis.ageCountAnalysis" [domain]="'pm'"></app-age-chart-react>
            <ng-template #angAgeChart>
              <app-chart [analysis]="selectedConcept.analyses.ageAnalysis" [pointWidth]="30" [chartTitle]="ageChartTitle"
                         [backgroundColor]="backgroundColor" [domainType]="domainType" [domainCountAnalysis]="domainCountAnalysis">
              </app-chart>
            </ng-template>
          </div>

          <!-- Todo wait on design for further dev -->
        </div>
      </div>
    </div>
  </div>
</div>

// public-ui/src/app/data-browser/views/pm/pm-react.component.tsx
import * as React from "react";

import { withRouteData } from "app/components/app-router";
import { AgeChartReactComponent } from "app/data-browser/charts/chart-age/chart-age-react.component";
import { ValueReactChartComponent } from "app/data-browser/charts/chart-measurement-values/chart-value-react.component";
import { GENDER_STRATUM_MAP } from "app/data-browser/charts/react-base-chart/base-chart.service";
import { TooltipReactComponent } from "app/data-browser/components/tooltip/tooltip-react.component";
import { dataBrowserApi } from "app/services/swagger-fetch-clients";
import { reactStyles } from "app/utils";
import { PM_CONCEPTS } from "app/utils/constants";
import { urlParamsStore } from "app/utils/navigation";
import { Spinner } from "app/utils/spinner";

const styles = reactStyles({
  pmContainer: {
    margin: "1.2em",
  },
  aside: {
    paddingRight: "18px",
    display: "block",
  },
  dbCard: {
    width: "100vw",
  },
  pmLayout: {
    display: "flex",
  },
  btnLink: {
    fontSize: "14px",
    color: "#0077b7",
    textAlign: 'left',
    textTransform:'uppercase',
    fontFamily:'GothamBook, Arial, sans-serif',
    padding: '0 0.5rem',
    height: '1.5rem',
    letterSpacing:'.12em'
  },
  btnList: {
    width:'14rem',
  },
  bsTitle: {
    paddingTop: "1em",
    paddingLeft: "1.5em",
  },
  chartLayout: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "1em",
  },
});

const PMGroups = [
  {
    group: "blood-pressure",
    groupName: "Mean Blood Pressure",
    concepts: [
      {
        conceptId: "903118",
        conceptName: "Systolic",
        chartType: "histogram",
        analyses: [],
      },
      {
        conceptId: "903115",
        conceptName: "Diastolic",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "height",
    groupName: "Height",
    concepts: [
      {
        conceptId: "903133",
        conceptName: "Height",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "weight",
    groupName: "Weight",
    concepts: [
      {
        conceptId: "903121",
        conceptName: "Weight",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "mean-waist",
    groupName: "Mean waist circumference",
    concepts: [
      {
        conceptId: "903135",
        conceptName: "Mean waist circumference",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "mean-hip",
    groupName: "Mean hip circumference",
    concepts: [
      {
        conceptId: "903136",
        conceptName: "Mean hip circumference",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "mean-heart-rate",
    groupName: "Mean heart rate",
    concepts: [
      {
        conceptId: "903126",
        conceptName: "Mean heart rate",
        chartType: "histogram",
        analyses: [],
      },
    ],
  },
  {
    group: "wheel-chair",
    groupName: "Wheelchair use",
    concepts: [
      {
        conceptId: "903111",
        conceptName: "Wheelchair use",
        chartType: "column",
        analyses: [],
      },
    ],
  },
  {
    group: "pregnancy",
    groupName: "Pregnancy",
    concepts: [
      {
        conceptId: "903120",
        conceptName: "Pregnancy",
        chartType: "column",
        analyses: [],
      },
    ],
  },
];

const styleCss = `
.active {
    font-weight: 900;
}
.bs-chart-item {
    width: calc((33.3%) - 18px);
    height: auto;
    flex-grow: 1;
}
.group-option {
    width: 100%;
    display: flex;
    justify-content: center;
}
.group-unit {
    display: flex;
    justify-content: center;
}
.unit-button {
    padding-right: 0.5em;
}
.unit-button.active, .concept-button.active {
    font-weight: 900;
    border-bottom: 4px solid #216fb4;
}
.group-button.active {
    font-weight: 3em;
    border: 2px solid #216fb4;
}
.participant-count {
    width: 100%;
    text-align: center;
    padding-bottom: 18px
}
aside .button-item button {
    font-size: 0.8em;
}
@media (max-width: 550px) {
    .db-card {
        overflow-x: scroll;
    }
}
.group-name {
    font-size: 1.4em;
    white-space: nowrap;
    width: fit-content;
    padding: 1em;
    padding-top: .5em;
    text-transform: capitalize;
}
.chart-item {
    width: calc((50%) - 18px);
    height: auto;
    flex-grow: 1;
}
.age-chart {
    padding: 1em;
    padding-left: 1.5em;
    margin: 0;
}

.chart-item:last-of-type {
    width: 100%;
    max-width: calc((100%) - 18px);
    min-width: 20rem;
}

@media (max-width: 978px) {
    .pm-layout {
        flex-direction: column;
    }
    aside {
        flex-wrap: wrap;
        display: flex;
        justify-content: space-between;
        margin: -1em;
        margin-bottom: 0px
    }
    aside .button-item {
        padding: 18px;
        padding-top: 0;
    }
    .chart-item {
        width: 100%;
        height: auto;
    }
}
`;

interface State {
  pmGroups: any;
  loading: boolean;
  selectedGroup: any;
  selectedConcept: any;
  selectedConceptUnit: any;
  selectedConceptValueAnalysis: any;
  selectedConceptValueCountAnalysis: any;
  domainCountAnalysis: any;
  unitNames: Array<String>;
}

export const PMReactComponent = withRouteData(
  class extends React.Component<{}, State> {
    constructor(props) {
      super(props);
      this.state = {
        pmGroups: PMGroups,
        loading: true,
        selectedGroup: PMGroups[0],
        selectedConcept: PMGroups[0].concepts[0],
        selectedConceptUnit: null,
        domainCountAnalysis: null,
        selectedConceptValueAnalysis: null,
        selectedConceptValueCountAnalysis: null,
        unitNames: [],
      };
    }

    componentDidMount() {
      this.getPMData();
      this.getPMCountData();
    }

    getPMData() {
      const { pmGroups } = this.state;
      const { search } = urlParamsStore.getValue();
      dataBrowserApi()
        .getConceptAnalysisResults(PM_CONCEPTS)
        .then((result) => {
          const items = result.items;
          for (const group of pmGroups) {
            for (const concept of group.concepts) {
              concept.analyses = items.filter(
                (item) => item.conceptId === concept.conceptId
              )[0];
              if (concept.conceptId === "903133") {
                const sortOrder = ["centimeter", "inch (us)"];
                concept.analyses.measurementGenderCountAnalysis.sort((a, b) => {
                  return (
                    sortOrder.indexOf(a.unitName.toLowerCase()) -
                    sortOrder.indexOf(b.unitName.toLowerCase())
                  );
                });
              }
              this.arrangeConceptAnalyses(concept);
              this.setState({ loading: false });
            }
          }
          if (search) {
            this.setState({
              selectedGroup: pmGroups.filter((conceptgroup) =>
                conceptgroup.groupName
                  .toLowerCase()
                  .includes(search.toLowerCase())
              )[0],
            });
          } else {
            this.setState({ selectedGroup: pmGroups[0] });
          }
          this.setUnit(pmGroups[0].concepts[0]);
        });
    }

    getPMCountData() {
      dataBrowserApi()
        .getCountAnalysis("Physical Measurements", "pm")
        .then((result) => {
          this.setState({ domainCountAnalysis: result });
        });
    }

    organizeGenders(concept: any) {
      const analysis = concept.analyses.genderAnalysis;
      let male = null;
      let female = null;
      let other = null;

      // No need to do anything if only one gender
      if (analysis.results.length <= 1) {
        return;
      }
      const results = [];
      for (const g of analysis.results) {
        if (g.stratum2 === "8507") {
          male = g;
        } else if (g.stratum2 === "8532") {
          female = g;
        } else if (g.stratum2 === "0") {
          other = g;
        }
      }

      // Order genders how we want to display  Male, Female , Others
      if (male) {
        results.push(male);
      }
      if (female) {
        results.push(female);
      }
      if (other) {
        results.push(other);
      }
      analysis.results = results;
    }

    setAnalysisStratum(results: any) {
      for (const r of results) {
        if (r.analysisStratumName === null) {
          r.analysisStratumName = GENDER_STRATUM_MAP[r.stratum3];
        }
      }
    }

    arrangeConceptAnalyses(concept: any) {
      if (concept.analyses.genderAnalysis) {
        this.organizeGenders(concept);
      }

      let genders = ["8507", "8532", "0"];
      let prevResult;
      for (const gca of concept.analyses.measurementGenderCountAnalysis) {
        if (gca.results.length < 3) {
          for (const result of gca.results) {
            prevResult = result;
            genders = genders.filter((item) => item !== result.stratum3);
          }
          for (const gender of genders) {
            const missingResult = {
              ...prevResult,
              stratum3: gender,
              countValue: 20,
              sourceCountValue: 20,
            };
            gca.results.push(missingResult);
          }
        }
        this.setAnalysisStratum(gca.results);
      }
    }

    showMeasurement(pmConceptGroup: any, concept: any) {
      this.setUnit(concept);
      this.setState({
        selectedGroup: pmConceptGroup,
        selectedConcept: concept,
      });
    }

    setUnit(concept: any) {
      const unitNames = [];
      if (concept.analyses && concept.analyses.measurementGenderCountAnalysis) {
        for (const r of concept.analyses.measurementGenderCountAnalysis) {
          const tempUnitNames = r.results
            .map(({ stratum2 }) => stratum2)
            .filter((elem, index, self) => index === self.indexOf(elem));
          unitNames.push(...tempUnitNames);
        }
      }
      if (unitNames.length > 0) {
        this.setState(
          { selectedConceptUnit: unitNames[0], unitNames: unitNames },
          () => {
            this.setAnalysis();
          }
        );
      }
    }

    setConceptUnit(unit) {
      this.setState({ selectedConceptUnit: unit }, () => {
        this.setAnalysis();
      });
    }

    setAnalysis() {
      const { selectedConcept, selectedConceptUnit } = this.state;
      if (["903120", "903111"].indexOf(selectedConcept.conceptId) === -1) {
        this.setState({
          selectedConceptValueAnalysis:
            selectedConcept.analyses.measurementValueGenderAnalysis.filter(
              (a) =>
                a.unitName.toLowerCase() === selectedConceptUnit.toLowerCase()
            )[0],
          selectedConceptValueCountAnalysis:
            selectedConcept.analyses.measurementGenderCountAnalysis.filter(
              (a) =>
                a.unitName.toLowerCase() === selectedConceptUnit.toLowerCase()
            )[0],
        });
      }
    }

    getValueAnalysis() {
      const { selectedConceptValueAnalysis, selectedConcept } = this.state;
      return !selectedConceptValueAnalysis
        ? selectedConcept.analyses.measurementValueGenderAnalysis[0]
        : selectedConceptValueAnalysis;
    }

    getCountAnalysis() {
      const { selectedConcept, selectedConceptUnit } = this.state;
      const genderSort = ["Male", "Female", "Other"];
      return selectedConcept.analyses.measurementGenderCountAnalysis
        .filter((r) => r.unitName === selectedConceptUnit)[0]
        .results.sort((a, b) => {
          return (
            genderSort.indexOf(a.analysisStratumName) -
            genderSort.indexOf(b.analysisStratumName)
          );
        });
    }

    render() {
      const {
        loading,
        selectedGroup,
        selectedConcept,
        selectedConceptUnit,
        unitNames,
        domainCountAnalysis,
        pmGroups,
      } = this.state;
      return (
        <React.Fragment>
          <style>{styleCss}</style>
          <div style={styles.pmContainer}>
            <h1>Browse Program Physical Measurements</h1>
            {loading ? (
              <Spinner />
            ) : (
              <div className="pm-layout" style={styles.pmLayout}>
                <aside style={styles.aside}>
                  {pmGroups.map((pmConceptGroup, index) => {
                    const buttonClass =
                      selectedGroup === pmConceptGroup
                        ? "btn btn-link group-button active"
                        : "btn btn-link group-button";
                    return (
                      <div className="button-item" key={index}>
                        <button
                          className={buttonClass}
                          style={{...styles.btnLink, ...styles.btnList}}
                          onClick={() =>
                            this.showMeasurement(
                              pmConceptGroup,
                              pmConceptGroup.concepts[0]
                            )
                          }
                        >
                          {" "}
                          {pmConceptGroup.groupName}
                        </button>
                      </div>
                    );
                  })}
                </aside>
                <div className="db-card" style={styles.dbCard}>
                  <div className="db-card-inner">
                    <div className="db-card-header">
                      <div className="group-name">
                        {selectedGroup.groupName}
                      </div>
                      {selectedConcept &&
                      selectedConcept.analyses &&
                      selectedConcept.analyses
                        .measurementValueGenderAnalysis ? (
                        <div className="bs-title" style={styles.bsTitle}>
                          Sex Assigned At Birth
                          <TooltipReactComponent
                            tooltipKey="pmValueChartHelpText"
                            label="Physical Measurements tooltip hover"
                            searchTerm="TODO replace search text in here"
                            action={
                              "Hover on pm biological sex chart of concept" +
                              selectedConcept.conceptName
                            }
                          />
                        </div>
                      ) : null}
                      {selectedGroup &&
                      selectedGroup.concepts &&
                      selectedGroup.concepts.length > 1 ? (
                        <div className="group-option">
                          {selectedGroup.concepts.map((concept, index) => {
                            const btnClass =
                              selectedConcept === concept
                                ? "btn btn-link concept-button active"
                                : "btn-link btn concept-button";
                            return (
                              <button
                                className={btnClass}
                                key={index}
                                onClick={() =>
                                  this.showMeasurement(selectedGroup, concept)
                                }
                                style={styles.btnLink}
                              >
                                {concept.conceptName}
                              </button>
                            );
                          })}
                        </div>
                      ) : null}
                    </div>
                    {unitNames && unitNames.length > 1 ? (
                      <div className="group-unit">
                        {unitNames.map((unit, index) => {
                          const btnClass =
                            selectedConceptUnit === unit
                              ? "btn btn-link unit-button active"
                              : "btn btn-link unit-button";
                          return (
                            <button
                              className={btnClass}
                              key={index}
                              onClick={() => this.setConceptUnit(unit)}
                              style={styles.btnLink}
                            >
                              {unit}
                            </button>
                          );
                        })}
                      </div>
                    ) : null}
                    {selectedConcept &&
                    (selectedConcept.conceptId === "903111" ||
                      selectedConcept.conceptId === "903120") ? (
                      selectedConcept.analyses.countAnalysis.results[0]
                        .countValue > 20 ? (
                        <div className="participant-count">
                          Total Participant count:{" "}
                          {
                            selectedConcept.analyses.countAnalysis.results[0]
                              .countValue
                          }
                        </div>
                      ) : (
                        <div className="participant-count">
                          Total Participant count: &le;{" "}
                          {
                            selectedConcept.analyses.countAnalysis.results[0]
                              .countValue
                          }
                        </div>
                      )
                    ) : null}
                    <div className="chart-layout" style={styles.chartLayout}>
                      {selectedConcept &&
                      selectedConcept.analyses &&
                      selectedConcept.analyses
                        .measurementGenderCountAnalysis ? (
                        selectedConcept.conceptId !== "903111" &&
                        selectedConcept.conceptId !== "903120" &&
                        selectedConceptUnit ? (
                          <React.Fragment>
                            {this.getCountAnalysis().map((gender, index) => {
                              const chartKey = gender.stratum3 + "-" + index;
                              return (
                                <div className="bs-chart-item" key={chartKey}>
                                  <ValueReactChartComponent
                                    conceptId={selectedConcept.conceptId}
                                    valueAnalysis={this.getValueAnalysis()}
                                    genderId={gender.stratum3}
                                    chartTitle={
                                      gender.analysisStratumName +
                                      " - " +
                                      (gender.countValue <= 20 ? "&le; " : "") +
                                      gender.countValue.toLocaleString()
                                    }
                                    key={chartKey}
                                  />
                                </div>
                              );
                            })}
                          </React.Fragment>
                        ) : selectedConcept.analyses
                            .measurementValueGenderAnalysis ? (
                          <div className="chart-item stacked-chart-item">
                            <ValueReactChartComponent
                              conceptId={selectedConcept.conceptId}
                              valueAnalysis={
                                selectedConcept.analyses
                                  .measurementValueGenderAnalysis[0]
                              }
                              genderId="stacked gender"
                              chartTitle="stacked chart"
                            />
                          </div>
                        ) : null
                      ) : null}
                      {selectedConcept.analyses &&
                      selectedConcept.analyses.ageAnalysis ? (
                        <div className="chart-item age-chart">
                          <div className="bs-title" style={styles.bsTitle}>
                            Age When Physical Measurement Was Taken
                            <TooltipReactComponent
                              tooltipKey="pmAgeChartHelpText"
                              label="Physical Measurements tooltip hover"
                              searchTerm="TODO replace search text in here"
                              action={
                                "Hover on pm age chart of concept " +
                                selectedConcept.conceptName
                              }
                            />
                          </div>
                          <AgeChartReactComponent
                            ageAnalysis={selectedConcept.analyses.ageAnalysis}
                            ageCountAnalysis={
                              domainCountAnalysis.ageCountAnalysis
                            }
                            domain="pm"
                            selectedResult=""
                          />
                        </div>
                      ) : null}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </React.Fragment>
      );
    }
  }
);
