// public-ui/src/app/data-browser/views/fitbit-view/fitbit-view.component.ts
import { Component, OnInit } from '@angular/core';
import { TooltipService } from 'app/data-browser/services/tooltip.service';
import { DbConfigService } from 'app/utils/db-config.service';
import { DataBrowserService } from 'publicGenerated/api/dataBrowser.service';
import { Subscription as ISubscription } from 'rxjs/internal/Subscription';

@Component({
  selector: 'app-fitbit-view',
  templateUrl: './fitbit-view.component.html',
  styleUrls: ['../../../styles/template.css', './fitbit-view.component.css']
})
export class FitbitViewComponent implements OnInit {
  private subscriptions: ISubscription[] = [];
  loadingStack: any = [];
  fitbitConcepts: any = [];
  searchText: string = null;
  analyses: any;
  selectedAnalyses: any;
  selectedItem: string;
  selectedDisplay: string;
  domainCountAnalysis: any;
  totalCountAnalysis: any;
  constructor(private api: DataBrowserService, public dbc: DbConfigService,
    public tooltipService: TooltipService) {
    this.selectedItem = 'any Fitbit data';
    this.selectedDisplay = 'any Fitbit data';
  }

  loading() {
    return this.loadingStack.length > 0;
  }

  ngOnInit() {
    this.searchText = localStorage.getItem('searchText');
    this.fitbitConcepts.push({
      id: 1, displayName: 'any Fitbit data',
      conceptName: 'Any Fitbit Data', icon: 'fa-watch-fitness',
      tooltipKey: 'fitbitAllDataHelpText'
    });
    this.fitbitConcepts.push({
      id: 2, displayName: 'heart rate by zone summary',
      conceptName: 'Heart Rate (Summary)', icon: 'fa-heartbeat',
      tooltipKey: 'fitbitHeartZoneHelpText'
    });
    this.fitbitConcepts.push({
      id: 3, displayName: 'heart rate (minute-level)',
      conceptName: 'Heart rate (minute-level)', icon: 'fa-monitor-heart-rate',
      tooltipKey: 'fitbitHeartRateHelpText'
    });
    this.fitbitConcepts.push({
      id: 4, displayName: 'activity (daily summary)',
      conceptName: 'Activity (daily summary)', icon: 'fa-running',
      tooltipKey: 'fitbitActivityDailyHelpText'
    });
    this.fitbitConcepts.push({
      id: 5, displayName: 'activity intraday steps (minute-level)',
      conceptName: 'Activity intraday steps (minute-level)', icon: 'fa-walking',
      tooltipKey: 'fitbitActivityStepsHelpText'
    });

    this.loadingStack.push(true);
    this.subscriptions.push(this.api.getFitbitAnalysisResults(this.dbc.FITBIT_MEASUREMENTS)
      .subscribe({
        next: result => {
          this.analyses = result.items;
          for (const item of result.items) {
            const fitbitConcept = this.fitbitConcepts.filter(concept =>
              concept.conceptName.toLowerCase().includes(item.conceptId.toLowerCase()))[0];
            fitbitConcept['ageAnalysis'] = item.ageAnalysis;
            fitbitConcept['genderAnalysis'] = item.genderAnalysis;
            fitbitConcept['countAnalysis'] = item.countAnalysis;
            this.totalCountAnalysis = item.countAnalysis;
            fitbitConcept['participantCountAnalysis'] = item.participantCountAnalysis;
          }
          if (this.searchText) {
            const matchingConcepts = this.fitbitConcepts.filter(concept =>
              concept.conceptName.toLowerCase().includes(this.searchText.toLowerCase()));
            if (matchingConcepts && matchingConcepts.length > 0) {
              this.selectedItem = matchingConcepts[0].conceptName;
              this.selectedDisplay = matchingConcepts[0].displayName;
              this.selectedAnalyses = matchingConcepts[0];
            }
          }
          this.selectedAnalyses = result.items[0];
          // Process fitbit results
          this.loadingStack.pop();
        },
        error: err => {
          this.loadingStack.pop();
          console.log('Error: ', err);
        }
      }));

      this.loadingStack.push(true);
      this.subscriptions.push(this.api.getCountAnalysis('Fitbit', 'fitbit')
            .subscribe({
              next: result => {
                this.domainCountAnalysis = result;
                this.loadingStack.pop();
              },
              error: err => {
                this.loadingStack.pop();
                console.log('Error: ', err);
              }
            }));
  }

  setGraphs(conceptObj) {
    this.analyses.forEach(concept => {
      if (conceptObj.conceptName === concept.conceptId) {
        this.selectedAnalyses = concept;
      }
    });
    this.selectedItem = conceptObj.displayName;
    this.selectedDisplay = conceptObj.displayName;
  }

}

<div class="fm-container">
  <h1>Fitbit Data</h1>
  <div class="fm-layout">
    <div class="fm-menu">
      <ng-container *ngFor="let menuItem of fitbitConcepts">
        <div class="fm-menu-item-container">
          <div tabindex="0" (keydown.enter)="setGraphs(menuItem)"  (click)="setGraphs(menuItem)" class="fm-menu-item"
            [ngClass]="{'active': selectedItem == menuItem.displayName}"> <i class="fas {{menuItem.icon}}"></i>
            <div class="fm-menu-item-display"><span>{{menuItem.displayName}}</span>
              <app-tooltip-react *ngIf="testReact"
                                 [tooltipKey]="menuItem.tooltipKey"></app-tooltip-react>
              <app-tooltip [tooltipKey]="menuItem.tooltipKey" *ngIf="!testReact"></app-tooltip>
            </div>
          </div>
        </div>
      </ng-container>
    </div>

    <div [ngClass]= "{'loading-layout': loading()}" class="fm-body db-card">
      <app-spinner [loading]="loading()"></app-spinner>
      <ng-container *ngIf="!loading()">
        <h2>{{selectedDisplay}} </h2>
        <div class="fm-body-top">
          <div class="fm-chart">
            <div class="display-body">Participants with
              {{selectedDisplay}}
            </div>
            <chart-fitbit [concepts]='selectedAnalyses.participantCountAnalysis' [countAnalysis]="totalCountAnalysis"></chart-fitbit>
          </div>
          <div class="fm-chart">
            <div class="display-body">Sex assigned at birth</div>
            <app-biosex-chart-react [genderAnalysis]='selectedAnalyses.genderAnalysis' [genderCountAnalysis]="domainCountAnalysis.genderCountAnalysis" [domain]="'fitbit'"></app-biosex-chart-react>
          </div>
        </div>
        <div class="fm-body-bottom">
          <div class="fm-chart">
            <div class="display-body">Age when physical measurement taken</div>
            <app-age-chart-react [ageAnalysis]='selectedAnalyses.ageAnalysis' [ageCountAnalysis]="domainCountAnalysis.ageCountAnalysis" [domain]="'fitbit'"></app-age-chart-react>
            <chart-age [concepts]='selectedAnalyses.ageAnalysis' [ageCountAnalysis]="domainCountAnalysis.ageCountAnalysis"></chart-age>
          </div>
        </div>
      </ng-container>
    </div>
  </div>
</div>

// public-ui/src/app/data-browser/views/fitbit-view/fitbit-view-react.component.tsx
import {withRouteData} from 'app/components/app-router';
import { AgeChartReactComponent } from 'app/data-browser/charts/chart-age/chart-age-react.component';
import { BioSexChartReactComponent } from 'app/data-browser/charts/chart-biosex/chart-biosex-react.component';
import { ChartFitbitReactComponent } from 'app/data-browser/charts/chart-fitbit/chart-fitbit-react.component';
import { TooltipReactComponent } from 'app/data-browser/components/tooltip/tooltip-react.component';
import { dataBrowserApi } from 'app/services/swagger-fetch-clients';
import { reactStyles } from 'app/utils';
import { fitbitConcepts } from 'app/utils/constants';
import { urlParamsStore } from 'app/utils/navigation';
import { Spinner } from 'app/utils/spinner';
import * as React from 'react';

const styles = reactStyles({
    fmLayout: {
        display: 'grid',
        gridTemplateColumns: '20% 80%',
        columnGap: '0.5rem'
    },
    fmBody: {
        background: 'white',
        borderRadius: '3px',
        padding: '2rem',
        paddingTop: '0'
    },
    fas: {
        paddingRight: '0.25em',
        fontSize: '2em'
    },
    fmMenuItemDisplay: {
        color: '#0079b8',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%'
    },
    fmMenuItem: {
        display: 'flex',
        alignItems: 'center',
        padding: '0.5rem',
        fontSize: '0.8em',
        /* border-bottom: 1px solid #262262 ; */
        cursor: 'pointer'
    },
    fmMenuItemActive: {
        display: 'flex',
        alignItems: 'center',
        padding: '0.5rem',
        fontSize: '0.8em',
        /* border-bottom: 1px solid #262262 ; */
        cursor: 'pointer',
        background: '#dae6ed',
        borderRadius: '3px',
        fontFamily: 'GothamBold'
    },
    selectedDisplayH: {
        paddingBottom: '1rem',
        textTransform: 'capitalize'
    },
    fmBodyTop: {
        display: 'flex',
        justifyContent: 'space-between'
    },
    fmBodyBottom: {
        paddingTop: '1rem',
        display: 'flex',
        justifyContent: 'center',
        width: '100%'
    },
    fmBottomChart: {
        background: '#216fb40d',
        padding: '1rem',
        borderRadius: '3px',
        minWidth: '15rem',
        paddingTop: '1rem',
        width: '100%'
    },
    fmMenuItemContainer: {
        padding: '0.25rem 0rem',
        borderBottom: '1px solid #262262',
        cursor: 'pointer'
    },
    chartDisplayBody: {
        paddingBottom: '1rem'
    },
    fmChart: {
        background: '#216fb40d',
        width: 'calc(50% - 0.5rem)',
        padding: '1rem',
        borderRadius: '3px',
        minWidth: '15rem'
    },
    displayName: {
        textTransform: 'capitalize'
    }
});

const styleCss = `
@media (max-width: 900px) {
    .fm-body-top .fm-chart {
        width: 100%;
    }
    .fm-body-top .fm-chart:last-of-type {
        width: 100%;
        margin-top: 1rem;
    }
}
`;

interface State {
    concepts: any;
    domainCountAnalysis: any;
    totalCountAnalysis: any;
    selectedItem: any;
    selectedDisplay: any;
    selectedAnalyses: any;
    loading: boolean;
}

export const FitbitReactComponent = withRouteData(class extends React.Component<{}, State> {
  constructor(props) {
    super(props);
    this.state = {concepts: fitbitConcepts, domainCountAnalysis: null, totalCountAnalysis: null, selectedItem: 'any Fitbit data',
    selectedDisplay: 'any Fitbit data', selectedAnalyses: null, loading: true};
  }

  componentDidMount() {
    this.getFitbitData();
    this.getCountData();
  }

  getFitbitData() {
    const {concepts} = this.state;
    const {search} = urlParamsStore.getValue();
    const FITBIT_MEASUREMENTS = ['Any Fitbit Data', 'Heart Rate (Summary)', 'Heart rate (minute-level)', 'Activity (daily summary)', 'Activity intraday steps (minute-level)'];
    dataBrowserApi().getFitbitAnalysisResults(FITBIT_MEASUREMENTS).then(
      (result) => {
        let totalCountAnalysis = null;
        for (const item of result.items) {
            const fitbitConcept = concepts.filter(concept =>
              concept.conceptName.toLowerCase().includes(item.conceptId.toLowerCase()))[0];
            fitbitConcept['ageAnalysis'] = item.ageAnalysis;
            fitbitConcept['genderAnalysis'] = item.genderAnalysis;
            fitbitConcept['countAnalysis'] = item.countAnalysis;
            totalCountAnalysis = item.countAnalysis;
            fitbitConcept['participantCountAnalysis'] = item.participantCountAnalysis;
       }
       let selectedItem = this.state.selectedItem;
       let selectedDisplay = this.state.selectedDisplay;
       let selectedAnalyses = result.items[0];
       if (search) {
        const matchingConcepts = concepts.filter(concept =>
                     concept.conceptName.toLowerCase().includes(search.toLowerCase()));
        if (matchingConcepts && matchingConcepts.length > 0) {
            selectedItem = matchingConcepts[0].conceptName;
            selectedDisplay = matchingConcepts[0].displayName;
            selectedAnalyses = matchingConcepts[0];
        }
       }
       this.setState({concepts: concepts, totalCountAnalysis: totalCountAnalysis, selectedItem: selectedItem,
       selectedDisplay: selectedDisplay, selectedAnalyses: selectedAnalyses, loading: false});
    });
  }

  getCountData() {
    console.log('testing new eoute change trigger');
    dataBrowserApi().getCountAnalysis('Fitbit', 'fitbit').then(
        (result) => {
            this.setState({domainCountAnalysis: result});
    });
  }

  setGraphs(concept) {
    this.setState({selectedAnalyses: concept, selectedItem: concept.displayName, selectedDisplay: concept.displayName});
  }

  render() {
    const {concepts, selectedDisplay, selectedAnalyses, totalCountAnalysis,
    domainCountAnalysis, loading} = this.state;
    const {search} = urlParamsStore.getValue();
    const tabIndex = 0;
    const selectedResult = null;
    return <React.Fragment>
        <style>{styleCss}</style>
        <div className='fm-container'>
            <h1>Fitbit Data</h1>
            {loading && <Spinner />}
            {!loading &&
            <div className='fm-layout' style={styles.fmLayout}>
                <div className='fm-menu'>
                    { concepts && concepts.map((concept, index) => {
                        const iconClass = 'fas ' + concept.icon;
                        const conceptClass = selectedDisplay.toLowerCase() === concept.displayName.toLowerCase() ?
                        styles.fmMenuItemActive : styles.fmMenuItem;
                        return <div className='fm-menu-item-container' style={styles.fmMenuItemContainer} key={index}>
                            <div tabIndex={tabIndex} style={conceptClass} onClick={() => this.setGraphs(concept)}>
                                <i className={iconClass} style={styles.fas}></i>
                                <div className='fm-menu-item-display' style={styles.fmMenuItemDisplay}>
                                <span style={styles.displayName}>{concept.displayName}</span>
                                    <TooltipReactComponent tooltipKey={concept.tooltipKey}
                                    label='Fitbit concept Hover' searchTerm={search} action='Fitbit concept hover'/>
                                </div>
                            </div>
                        </div>;
                    })
                    }
                </div>
                <div className='fm-body' style={styles.fmBody}>
                    <h2 style={styles.selectedDisplayH}>{selectedDisplay} </h2>
                    <div className='fm-body-top' style={styles.fmBodyTop}>
                        <div className='fm-chart' style={styles.fmChart}>
                            <div className='display-body' style={styles.chartDisplayBody}>Participants with {selectedDisplay}</div>
                            {selectedAnalyses && totalCountAnalysis &&
                                <ChartFitbitReactComponent concepts={selectedAnalyses.participantCountAnalysis}
                                countAnalysis={totalCountAnalysis}/>
                            }
                        </div>
                        <div className='fm-chart' style={styles.fmChart}>
                        <div className='display-body' style={styles.chartDisplayBody}>Sex assigned at birth</div>
                        {selectedAnalyses && totalCountAnalysis && domainCountAnalysis &&
                        <BioSexChartReactComponent genderAnalysis={selectedAnalyses.genderAnalysis}
                        genderCountAnalysis={domainCountAnalysis.genderCountAnalysis}
                                                domain='fitbit' selectedResult={selectedResult}/>
                        }
                        </div>
                    </div>
                    <div className='fm-body-bottom' style={styles.fmBodyBottom}>
                        <div className='fm-chart' style={styles.fmBottomChart}>
                            <div className='display-body' style={styles.chartDisplayBody}>Age when physical measurement taken</div>
                            {selectedAnalyses && domainCountAnalysis &&
                                <AgeChartReactComponent ageAnalysis={selectedAnalyses.ageAnalysis}
                                ageCountAnalysis={domainCountAnalysis.ageCountAnalysis} domain='fitbit' selectedResult={selectedResult}/>
                            }
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
      </React.Fragment>;
    }
});
