// public-ui/src/app/data-browser/views/error-message/error-message-react.component.tsx
import * as React from "react";

import { BaseReactWrapper } from "app/data-browser/base-react/base-react.wrapper";
import { ClrIcon } from "app/utils/clr-icon";

const css = `
.alert,
.alert-box,
.error-message {
  background-color: #f7981d;
  border-radius: 5px;
  border-color: #f7981d;
  color: white;
  display: inline-block;
  font-size: 1.25em;
  padding: 1%;
}
.alert-icon {
  color: white;
}
`;

interface Props {
  dataType: string;
}

export class ErrorMessageReactComponent extends React.Component<Props, {}> {
  constructor(props: Props) {
    super(props);
  }

  render() {
    const { dataType } = this.props;
    return (
      <React.Fragment>
        <style>{css}</style>
        <div className="alert alert-box">
          <ClrIcon
            shape="alert-icon"
            className="exclamation-triangle"
            style={{ width: 26, height: 26 }}
          />
          <span className="alert-text">
            {dataType === "data"
              ? "Sorry, the data are currently unavailable. Please try refreshing the page or returning home."
              : "Sorry, the chart cannot be displayed. Please try refreshing the page"}
          </span>
        </div>
      </React.Fragment>
    );
  }
}

// public-ui/src/app/data-browser/views/error-message/error-message.component.ts
import { Component, Input, OnInit } from "@angular/core";

@Component({
  selector: "app-error-message",
  templateUrl: "./error-message.component.html",
  styleUrls: ["./error-message.component.css", "../../../styles/page.css"],
})
export class ErrorMessageComponent implements OnInit {
  @Input() dataType: string;

  constructor() {}

  ngOnInit() {}
}

<div class="alert alert-box">
  <div class="alert-items">
    <div class="alert-item static">
      <div class="alert-icon-wrapper">
        <clr-icon
          class="alert-icon"
          shape="exclamation-triangle"
          size="26"
        ></clr-icon>
      </div>
      <span class="alert-text" *ngIf="dataType === 'data'; else chart_alert">
        Sorry, the data are currently unavailable. Please try refreshing the
        page or returning home <a [routerLink]="['']">here.</a>
      </span>
      <ng-template #chart_alert>
        <span class="alert-text">
          Sorry, the chart cannot be displayed. Please try refreshing the page.
        </span>
      </ng-template>
    </div>
  </div>
</div>
