// public-ui/src/app/data-browser/views/intro-vids/intro-vids_react/intro-vids_react.component.tsx
import * as React from 'react';
import { FunctionComponent } from 'react';
import { Video } from '../../../services/video.service';


export const IntroVidReactComponent: FunctionComponent<Video> =
    (props) => {
        return <span>
            <h2 className='secondary-display'>{props.title}</h2>
            <div className='vid-container'>
                <video poster={props.poster} controls >
                    {
                        props.src.map((source) => {
                            return <source key={source.url} src={source.url} type={source.type} />;
                        })
                    }
                    {
                        props.subtitles.map((sub) => {
                            return <track
                                key={sub.label} default={sub.default} label={sub.label}
                                lang={sub.lang} src={sub.url}></track>;
                        })
                    }
                    Sorry, your browser doesn't support embedded videos,
                     but don't worry, you can <a href={props.downloadUrl}>download it</a>
                    and watch it with your favorite video player!
                </video>
            </div>
        </span>;
    };

// public-ui/src/app/views/intro-vids/intro-vids.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-intro-vids',
  templateUrl: './intro-vids.component.html',
  styleUrls: ['../../styles/template.css', './intro-vids.component.css']
})
export class IntroVidsComponent {

  videos = [{
    title: 'Participant Intro',
    downloadUrl: '',
    poster: '/assets/videos/video_poster.png',
    src: [{
      url: '',
      type: 'video/mp4'
    },
    {
      url: '',
      type: 'video/ogg'
    },
    {
      url: '',
      type: 'video/webm'
    }],
  },
  {
    title: 'Researcher Intro',
    downloadUrl: '',
    poster: '/assets/videos/video_poster.png',
    src: [{
      url: '',
      type: 'video/mp4'
    },
    {
      url: '',
      type: 'video/ogg'
    },
    {
      url: '',
      type: 'video/webm'
    }],
  }];

}

<div class="db-container">
  <h1 class="primary-display">Introductory Videos</h1>

  <ng-container *ngFor="let video of videos">
    <h2 class="secondary-display">{{video.title}}</h2>
    <div class="vid-container">
      <video poster="{{video.poster}}"controls >
        <ng-container *ngFor='let src of video.src'>
          <source src="{{src.url}}" type="{{src.type}}" />
        </ng-container>
          Sorry, your browser doesn't support embedded videos,
          but don't worry, you can <a href="{{video.downloadUrl}}">download it</a>
          and watch it with your favorite video player!
      </video>
    </div>
  </ng-container>
</div>
